asystem:
  molecule: poly
  project: unit-test
  seed: 0
  type: train
  device: cuda

logger:
  date: test-run
  freq_rollout_save: 100
  server: server

policy:
  force: True
  goal_conditioned: False

sampling:
  start_states: c5
  end_states: c7ax
  num_steps: 500
  num_samples: 16
  temperature: 0

training:
  loss: tb
  learning_rate: 0.001
  std: 0.1
  start_std: 0.2
  end_std: 0.1
  hindsight: True
  num_rollouts: 10000
  trains_per_rollout: 2000
  buffer_size: 100
  terminal_std: 0.05
  max_grad_norm: 10
