asystem:
  molecule: alanine
  project: unit-test
  seed: 0
  type: train
  device: cuda
  wandb: True

logger:
  date: test-run
  freq_rollout_save: 8
  server: server

policy:
  force: True
  goal_conditioned: False

sampling:
  start_states: c5
  end_states: c7ax
  num_steps: 100
  num_samples: 4
  temperature: 0

training:
  loss: tb
  learning_rate: 0.01
  std: 0.1
  start_std: 0.1
  end_std: 0.05
  # hindsight: True
  num_rollouts: 32
  trains_per_rollout: 100
  buffer_size: 100
  terminal_std: 0.2
  max_grad_norm: 10
